### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by antgr** [UKPLab/acl2019-BERT-argument-classification-and-clustering#1]
Hi,
thanks for sharing this work.
I tried to run one of the scripts, but seems that datasets are missing, so I take the following error
Traceback (most recent call last):
  File "train.py", line 711, in <module>
    main()
  File "train.py", line 571, in main
    train_sampler = RandomSampler(train_data)
  File "/home/ant/anaconda3/envs/pytorch_full/lib/python3.7/site-packages/torch/utils/data/sampler.py", line 94, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0

From where I am supposed to download the data?

Thanks,
Antonis

**Comment by antgr** [comment]
I downloaded the data from here ```https://www.informatik.tu-darmstadt.de/ukp/research_6/data/argumentation_mining_1/ukp_sentential_argument_mining_corpus/index.en.jsp```
I created the following directory structure
```ls datasets/ukp/data/
complete  incomplete```
where data directory was copied from UKP_Sentential_Argument_Mining_Corpus/UKP\ Sentential\ Argument\ Mining\ Corpus/data
but I see that ```data/complete``` is empty, although train_ukp.sh expects that it is not.
(I replaced ```data/complete``` with data/incomplete` in the script and now it is able to run and train.
Any comment suggestion? Also I noticed that it didn't use any pretrained model. Are the pretrained models trained in ukp dataset, or it means something like BERT?

**Comment by antgr** [comment]
OK, I read the readme instructions. The Java program displays after a while this message continuously:
``` Warning: Couldn't find sentence '3350ec033187e0182a6ed575a99c8349' ```
Is something wrong from my part?

**Comment by antgr** [comment]
@nreimers  are you aware of that issue? I currently  do not need to work with the code, but I am still curious if that is a known issue.

**Comment by nreimers** [comment]
Hi @antgr 
Due to copyright issues, it is sadly not possible do directly share the dataset. To by-pass this issue, it crawls the source document from archive.org.

It appears that one of the links / source document disappeared (404). Sadly I'm not the author of the dataset, so I don't know if it can be fixed.

If you are interested in this dataset, please contact me by email: Rnils@web.de

**Comment by antgr** [comment]
Thank you I sent you an email!
