### ISSUE TITLE
question on argument similarity task

### ISSUE THREAD

**Issue by XuShiqiang9894** [UKPLab/acl2019-BERT-argument-classification-and-clustering#6]
Hello,
I find there is no File (make_splits.py)

**Comment by nreimers** [comment]
@XuShiqiang9894 
Thanks for pointing this out. I added the file to git:
https://github.com/UKPLab/acl2019-BERT-argument-classification-and-clustering/blob/master/argument-similarity/datasets/ukp_aspect/make_splits.py

**Comment by XuShiqiang9894** [comment]
@nreimers Thank you very much！
